###
#
# Build the image for xgboost development environment
# on Centos7 with lower version of GLIBC.
#
# Arguments: CUDA_VER=9.2 or 10.0
#
###
ARG CUDA_VER=10.0
FROM nvidia/cuda:$CUDA_VER-devel-centos7

ARG CUDA_VER

### Install basic requirements
RUN yum install -y zlib-devel bzip2 centos-release-scl
RUN yum install -y devtoolset-7 boost-devel

### Install nccl
ENV NV_REPO_NAME nvidia-machine-learning-repo-rhel7-1.0.0-1.x86_64.rpm
ENV NV_REPO_URL https://developer.download.nvidia.com/compute/machine-learning/repos/rhel7/x86_64/$NV_REPO_NAME
RUN curl -O $NV_REPO_URL && \
    rpm -i $NV_REPO_NAME && \
    yum update -y && \
    yum install -y \
        libnccl-2.4.7-1+cuda$CUDA_VER \
        libnccl-devel-2.4.7-1+cuda$CUDA_VER \
        libnccl-static-2.4.7-1+cuda$CUDA_VER && \
    rm -f $NV_REPO_NAME

### Install conda and cudf
ENV CONDA_FILE Miniconda3-4.6.14-Linux-x86_64.sh
RUN curl -O https://repo.continuum.io/miniconda/$CONDA_FILE && \
    bash $CONDA_FILE -b -p /opt/conda && \
    rm -f $CONDA_FILE

ENV PATH=/opt/conda/bin/:$PATH
RUN conda init && \
    . ~/.bashrc && \
    conda install -y -c rapidsai-nightly/label/cuda$CUDA_VER \
        libcudf librmm \
        cmake maven
ENV JAVA_HOME  /opt/conda

