ARG LINUX_VERSION=ubuntu16.04
ARG CUDA_VER=10.0

FROM nvidia/cuda:${CUDA_VER}-devel-${LINUX_VERSION}

ARG CUDA_VER

# Install conda
ADD https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh /miniconda.sh
RUN sh /miniconda.sh -b -p /conda && /conda/bin/conda update -n base conda && \
    rm /miniconda.sh

ENV PATH=${PATH}:/conda/bin
# Enables "source activate conda"
RUN conda init && \
    . ~/.bashrc && \
    conda install -y cmake openjdk maven
RUN conda install -y -c rapidsai-nightly/label/cuda$CUDA_VER libcudf

RUN apt update && \
    apt install -y --allow-change-held-packages libnccl2=2.4.7-1+cuda$CUDA_VER libnccl-dev=2.4.7-1+cuda$CUDA_VER

WORKDIR /workspace
